baseURL = "https://foamscience.github.io/openfoam-with-neovim/"
languageCode = "en-us"
title = "Editing OpenFOAM cases with (Neo)VIM"

theme = "reveal-hugo"


[markup.goldmark.renderer]
unsafe = true
[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
highlight_theme = "a11y-light"
custom_css = "css/customized.css"
width = "1200"

[markup.highlight]
codeFences = false
